### ISSUE TITLE
STA9750 cliu98 MiniProject #00

### ISSUE THREAD

**Issue by cliu98** [cliu98/STA9750-2024-FALL#1]
Hi @michaelweylandt!

I've created my STA9750 website - check it out!

https://cliu98.github.io/STA9750-2024-FALL

**Comment by michaelweylandt** [comment]
Thanks @cliu98 !

Peer Feedback:

- @greazyz
- @ElissaLeung
- @bleuuuz

Please a look at the website associated with this GitHub repo
and provide some peer feedback to @cliu98.

Website URL should be: https://cliu98.github.io/STA9750-2024-FALL/

If that link doesn't work, please check out the GitHub profile for @cliu98 and
see if you can help them get it working.

At a minimum, please note:

1. Something you like about the submission.
2. A suggestion on how to improve it.

Feel free to link to other repos, the course documentation, or other useful
examples.

This submission is ungraded, so there's you don't need to provide
a numerical score.

Thanks!
@michaelweylandt

CC: @charles-ramirez

**Comment by bleuuuz** [comment]
Hey Chris! I think the link to your WIX website about your mechanical engineering portfolio is super sick. (The punch-out controller is probably my favorite part) Maybe you can add your resume/cover letter to your website in addition to your projects!

**Comment by ElissaLeung** [comment]
Hi @cliu98 ! I loved that you included a link to your undergraduate work in mechanical engineering, I enjoyed looking through your portfolio of projects! Hopefully, you'll be able to add a portfolio of data analytics/science projects on there by the end of the semester as well. Maybe you can include a professional headshot or visuals on your website. Otherwise, I really enjoyed exploring your submission and your mechanical engineering portfolio!

**Comment by greazyz** [comment]
Hi Chris! I like that you hyperlinked your portfolio within the
sentence instead of phrasing it as "my portfolio: here". You can play
around with markdowns, such as italics and emphasis. Aside from your
academic background, I would also like to get to know you more, with one or
2 personal facts!
